#ifndef __XS3_LED_DEV_H
#define __XS3_LED_DEV_H

#define XS3_LED_MAGIC 'q'
#define XS3_LED_ON  _IOW(XS3_LED_MAGIC, 1, unsigned long)
#define XS3_LED_OFF _IOW(XS3_LED_MAGIC, 0, unsigned long)

/* xs3led gpio
led1 : gpio0_20
led2 : gpio1_9
led3 : gpio1_8
*/

//led gpio
#define GPIO0_BASE_ADDR			(0x44E07000)
#define GPIO0_DATOUT_OFFSET		(0x13C)
#define GPIO0_SETDATOUT_OFFSET	(0x194)

#define GPIO1_BASE_ADDR			(0x4804C000)
#define GPIO1_DATOUT_OFFSET		(0x13C)
#define GPIO1_SETDATOUT_OFFSET	(0x194)

#define XS3_LED_1_GPCON 		(GPIO0_BASE_ADDR + GPIO0_SETDATOUT_OFFSET)
#define XS3_LED_2_GPCON			(GPIO1_BASE_ADDR + GPIO1_SETDATOUT_OFFSET)
#define XS3_LED_3_GPCON			(GPIO1_BASE_ADDR + GPIO1_SETDATOUT_OFFSET)

#define XS3_LED_1_GPDAT 		(GPIO0_BASE_ADDR + GPIO0_DATOUT_OFFSET )
#define XS3_LED_2_GPDAT			(GPIO1_BASE_ADDR + GPIO1_DATOUT_OFFSET )
#define XS3_LED_3_GPDAT			(GPIO1_BASE_ADDR + GPIO1_DATOUT_OFFSET )

#endif
